[package]
name = "neophanim"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]

[dev-dependencies]
rug = "1.22.0" # for constants testing

[lib]
name = "neophanim"
path = "src/lib.rs"
